export const NEGERI_SEMBILAN_DESTINATION = {
  // NEGERI SEMBILAN DISTRICT–TOWN MAPPING (complete, no duplicates)

  // 1. SEREMBAN DISTRICT
  seremban: "seremban",
  "seremban 2": "seremban",
  "seremban 3": "seremban",
  oakland: "seremban",
  rasah: "seremban",
  "rasah jaya": "seremban",
  sendayan: "seremban",
  "bandar sri sendayan": "seremban",
  labu: "seremban",
  mantin: "seremban",
  lenggeng: "seremban",
  pantai: "seremban",
  ampangan: "seremban",
  paroi: "seremban",
  senawang: "seremban",
  "taman tuanku jaafar": "seremban",
  "taman seremban jaya": "seremban",
  temiang: "seremban",
  mambau: "seremban",
  "rasah kemayan": "seremban",
  "forest heights": "seremban",
  "bukit kepayang": "seremban",
  "jalan labu": "seremban",
  "taman ast": "seremban",
  "taman seremban putra": "seremban",
  "seri pajam": "seremban",
  pajam: "seremban",

  // 2. PORT DICKSON DISTRICT
  "port dickson": "port dickson",
  "tanjung tuan": "port dickson",
  lukut: "port dickson",
  "sungai menyala": "port dickson",
  "si rantau panjang": "port dickson",
  "bagan pinang": "port dickson",
  "teluk kemang": "port dickson",
  "ayer keroh": "port dickson",
  "batu 4 jalan pantai": "port dickson",
  "pantai cahaya negeri": "port dickson",
  sirok: "port dickson",
  "pengkalan kemaman": "port dickson",
  "bandar springhill": "port dickson",
  "tanah merah site c": "port dickson",
  "bandar sri sendayan (coastal)": "port dickson",

  // 3. REMBAU DISTRICT
  rembau: "rembau",
  chembong: "rembau",
  kendong: "rembau",
  pedas: "rembau",
  chengkau: "rembau",
  gadong: "rembau",
  "tampin linggi border": "rembau",
  "sembilan estate": "rembau",
  kundur: "rembau",
  "kampung batu": "rembau",
  "tanjung rimau": "rembau",
  "kampung sepri": "rembau",
  solok: "rembau",

  // 4. TAMPIN DISTRICT
  tampin: "tampin",
  gemas: "tampin",
  "gemas baharu": "tampin",
  repah: "tampin",
  "air kuning selatan": "tampin",
  gemencheh: "tampin",
  "batang melaka": "tampin",
  "kampung ulu jempol": "tampin",
  "felda jelai": "tampin",
  "felda gemas": "tampin",
  "felda jelai 1": "tampin",
  "felda jelai 2": "tampin",
  "felda jelai 3": "tampin",
  "felda pasoh dua": "tampin",
  "bukit residen": "tampin",

  // 5. JELEBU DISTRICT
  jelebu: "jelebu",
  "kampung chennah": "jelebu",
  "petaling jelebu": "jelebu",
  "simenyih border": "jelebu",
  "kuala klawang": "jelebu",
  pertang: "jelebu",
  titi: "jelebu",
  kenaboi: "jelebu",
  "jeram toi": "jelebu",
  "triang hilir": "jelebu",
  "kampung gagu": "jelebu",
  "kampung sungai durian": "jelebu",
  "kampung baru petasih": "jelebu",

  // 6. JEMPOL DISTRICT
  jempol: "jempol",
  bahau: "jempol",
  "bandar seri jempol": "jempol",
  "felda raja alias": "jempol",
  "felda raja alias 1": "jempol",
  "felda raja alias 2": "jempol",
  "felda raja alias 3": "jempol",
  jelai: "jempol",
  rombongan: "jempol",
  mahsan: "jempol",
  "taman bukit kelulut": "jempol",
  "kampung serting ulu": "jempol",
  serting: "jempol",
  "felda serting hilir": "jempol",
  "felda palong": "jempol",
  "felda palong 1": "jempol",
  "felda palong 2": "jempol",
  "felda palong 3": "jempol",
  "felda palong 4": "jempol",
  "felda palong 5": "jempol",
  "felda palong 6": "jempol",
  "felda palong 7": "jempol",
  "felda palong 8": "jempol",
  "felda palong 9": "jempol",
  "felda palong 10": "jempol",
  "felda palong 11": "jempol",
  "felda palong 12": "jempol",
  "felda palong 13": "jempol",
  "felda palong 14": "jempol",
  "felda palong 15": "jempol",
  "felda palong 16": "jempol",
  "felda palong 17": "jempol",
  "felda palong 18": "jempol",
  "felda palong 19": "jempol",
  "felda palong 20": "jempol",
  "felda palong 21": "jempol",
  "felda palong 22": "jempol",

  // 7. KUALA PILAH DISTRICT
  "kuala pilah": "kuala pilah",
  juasseh: "kuala pilah",
  "parit tinggi": "kuala pilah",
  "kampung parit": "kuala pilah",
  "seri menanti": "kuala pilah",
  pelangai: "kuala pilah",
  umpong: "kuala pilah",
  "bahau border": "kuala pilah",
  "tanjung ipoh": "kuala pilah",
  pilah: "kuala pilah",
  panchor: "kuala pilah",
  "felda sri jaya": "kuala pilah",
  "kampung tampin ulu": "kuala pilah",
  "kampung batu kikir": "kuala pilah",
  "juasseh baru": "kuala pilah",
  "taman tuanku kurshiah": "kuala pilah",
};
