export const SELANGOR_DESTINATION = {
  // SELANGOR DISTRICT–TOWN MAPPING (complete, standardized)

  // 1. PETALING DISTRICT
  "petaling jaya": "petaling",
  pj: "petaling",
  "subang jaya": "petaling",
  "shah alam": "petaling",
  puchong: "petaling",
  "bandar sunway": "petaling",
  sunway: "petaling",
  "seri kembangan": "petaling",
  "bukit jalil": "petaling",
  "old klang road": "petaling",
  "bandar utama": "petaling",
  "kota damansara": "petaling",
  "ara damansara": "petaling",
  tropicana: "petaling",
  "damansara utama": "petaling",
  "damansara perdana": "petaling",
  "bandar sri damansara": "petaling",
  "mutiara damansara": "petaling",
  "sekysen 17": "petaling",
  "sekysen 14": "petaling",
  usj: "petaling",
  "putra heights": "petaling",
  elmina: "petaling",
  "bukit jelutong": "petaling",
  "denai alam": "petaling",
  "alam megah": "petaling",

  // 2. KLANG DISTRICT
  klang: "klang",
  "port klang": "klang",
  "pelabuhan klang": "klang",
  "bandar botanik": "klang",
  "bandar bukit tinggi": "klang",
  "bukit raja": "klang",
  kapar: "klang",
  meru: "klang",
  pandamaran: "klang",
  "telok gong": "klang",
  "taman sentosa klang": "klang",
  "telok menegun": "klang",
  "rimbayu klang": "klang",
  "glenmarie cove": "klang",
  "ambang botanic": "klang",
  "bandar bukit raja": "klang",

  // 3. HULU LANGAT DISTRICT
  "hulu langat": "hulu langat",
  kajang: "hulu langat",
  ampang: "hulu langat",
  cheras: "hulu langat",
  bangi: "hulu langat",
  "bandar baru bangi": "hulu langat",
  semenyih: "hulu langat",
  beranang: "hulu langat",
  balakong: "hulu langat",
  "taman connaught": "hulu langat",
  "taman suntex": "hulu langat",
  "bukit mahkota": "hulu langat",
  "desa serdang": "hulu langat",
  "bandar teknokrat": "hulu langat",
  "batang siang": "hulu langat",
  "taman cuepacs": "hulu langat",
  "saujana impian": "hulu langat",
  "lembah jaya": "hulu langat",
  "taman bukit mewah": "hulu langat",

  // 4. GOMBAK DISTRICT
  gombak: "gombak",
  "batu caves": "gombak",
  selayang: "gombak",
  rawang: "gombak",
  "batu arang": "gombak",
  kuang: "gombak",
  kundang: "gombak",
  "taman melawati": "gombak",
  "wangsa maju": "gombak",
  setapak: "gombak",
  "taman permata": "gombak",
  "taman sri gombak": "gombak",
  "bukit rahman putra": "gombak",
  "bandar country homes": "gombak",
  "sungai buloh": "gombak",
  "kampung setia": "gombak",
  "kampung melayu sri kundang": "gombak",
  "bandar tasik puteri": "gombak",

  // 5. HULU SELANGOR DISTRICT
  "hulu selangor": "hulu selangor",
  "batang kali": "hulu selangor",
  "bukit beruntung": "hulu selangor",
  "bukit sentosa": "hulu selangor",
  serendah: "hulu selangor",
  kerling: "hulu selangor",
  rasa: "hulu selangor",
  "ulu yam": "hulu selangor",
  "ulu yam baru": "hulu selangor",
  peretak: "hulu selangor",
  "ampang pecah": "hulu selangor",
  kalumpang: "hulu selangor",
  "genting malek": "hulu selangor",
  "kampung gurney": "hulu selangor",

  // 6. KUALA SELANGOR DISTRICT
  "kuala selangor": "kuala selangor",
  ijok: "kuala selangor",
  "bestari jaya": "kuala selangor",
  "batang berjuntai": "kuala selangor",
  "tanjung karang": "kuala selangor",
  "pasir penambang": "kuala selangor",
  jeram: "kuala selangor",
  "puncak alam": "kuala selangor",
  "kampung kuantan": "kuala selangor",
  "kampung bukit belimbing": "kuala selangor",

  // 7. KUALA LANGAT DISTRICT
  "kuala langat": "kuala langat",
  banting: "kuala langat",
  jenjarom: "kuala langat",
  "telok panglima garang": "kuala langat",
  "tanjung sepat": "kuala langat",
  morib: "kuala langat",
  "bandar saujana putra": "kuala langat",
  "bandar rimbayu": "kuala langat",
  "bukit changgang": "kuala langat",
  "kampung labohan dagang": "kuala langat",
  kelanang: "kuala langat",
  sijangkang: "kuala langat",
  chendu: "kuala langat",

  // 8. SABAK BERNAM DISTRICT
  "sabak bernam": "sabak bernam",
  "sungai besar": "sabak bernam",
  sekincan: "sabak bernam",
  "bagan terap": "sabak bernam",
  "pancang bedena": "sabak bernam",
  "kampung sungai nipah": "sabak bernam",
  "parit baru": "sabak bernam",
  "parit 10": "sabak bernam",
  "kampung sungai air tawar": "sabak bernam",
  "kampung sungai haji dorani": "sabak bernam",

  // 9. SEPANG DISTRICT
  sepang: "sepang",
  dengkil: "sepang",
  "salak tinggi": "sepang",
  "bandar baru salak tinggi": "sepang",
  "putrajaya outskirts": "sepang",
  cyberjaya: "sepang",
  "kampung labu": "sepang",
  "bandar enstek": "sepang",
  klia: "sepang",
  klia2: "sepang",
  "bandar serenia": "sepang",
  "sungai pelek": "sepang",
  "tanjung mas": "sepang",
  "bagan lalang": "sepang",
  "lukut border": "sepang",
  "kampung baru salak": "sepang",
};
