name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

      - name: Run build
        run: npm run build
        env:
          # Skip telemetry during CI
          NEXT_TELEMETRY_DISABLED: 1

      - name: Validate Prisma schema
        if: hashFiles('prisma/schema.prisma') != ''
        run: npx prisma validate
        env:
          # Provide dummy DATABASE_URL for schema validation
          DATABASE_URL: postgresql://user:pass@localhost:5432/fishon

      - name: Run tests
        run: npm test || true
        continue-on-error: true
